# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] "
      prefix: "[github-actions] "

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    versioning-strategy: increase-if-necessary
    groups:
      "Python Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[python] "
      prefix: "[python] "

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    versioning-strategy: increase
    groups:
      "NPM Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[npm] "
      prefix: "[npm] "
