noData = [
    {
        "ratting": [],
        "total": {
            "total_amount": "0.00",
            "total_amount_ess": "0.00",
            "total_amount_all": "0.00",
            "total_amount_mining": "0",
            "total_amount_others": "0.00",
            "total_amount_costs": "0.00",
        },
        "billboard": {
            "walletcharts": None,
            "charts": [],
            "rattingbar": None,
            "workflowgauge": None,
        },
    }
]

CharmonthlyMarch = [
    {
        "ratting": [
            {
                "main_id": 1001,
                "main_name": "Gneuten",
                "total_amount": "200000.00",
                "total_amount_ess": "1133333.333333333333333333333",
                "total_amount_mining": "200000",
                "total_amount_others": "200000.00",
                "total_amount_costs": "-200000.00",
            }
        ],
        "total": {
            "total_amount": "200000.00",
            "total_amount_ess": "1133333.333333333333333333333",
            "total_amount_all": "1533333.333333333333333333333",
            "total_amount_mining": "200000",
            "total_amount_others": "200000.00",
            "total_amount_costs": "-200000.00",
        },
        "billboard": {
            "walletcharts": [
                ["Income", 400000],
                ["Market Cost", 100000],
                ["Production Cost", 100000],
                ["Misc. Cost", 0],
            ],
            "charts": [],
            "rattingbar": [
                [
                    "x",
                    "2024-06-01",
                    "2024-06-02",
                    "2024-06-03",
                    "2024-06-04",
                    "2024-06-05",
                    "2024-06-06",
                    "2024-06-07",
                    "2024-06-08",
                    "2024-06-09",
                    "2024-06-10",
                    "2024-06-11",
                    "2024-06-12",
                    "2024-06-13",
                    "2024-06-14",
                    "2024-06-15",
                    "2024-06-16",
                    "2024-06-17",
                    "2024-06-18",
                    "2024-06-19",
                    "2024-06-20",
                    "2024-06-21",
                    "2024-06-22",
                    "2024-06-23",
                    "2024-06-24",
                    "2024-06-25",
                    "2024-06-26",
                    "2024-06-27",
                    "2024-06-28",
                    "2024-06-29",
                    "2024-06-30",
                ],
                [
                    "Ratting",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "ESS Payout",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1133333,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "Miscellaneous",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "Mining",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
            ],
            "workflowgauge": [
                ["Ratting", 11.5],
                ["ESS Payout", 65.3],
                ["Miscellaneous", 11.5],
                ["Mining", 11.5],
            ],
        },
    }
]

Charyearly = [
    {
        "ratting": [
            {
                "main_id": 1001,
                "main_name": "Gneuten",
                "total_amount": "300000.00",
                "total_amount_ess": "1133333.333333333333333333333",
                "total_amount_mining": "200000",
                "total_amount_others": "200000.00",
                "total_amount_costs": "-200000.00",
            }
        ],
        "total": {
            "total_amount": "300000.00",
            "total_amount_ess": "1133333.333333333333333333333",
            "total_amount_all": "1633333.333333333333333333333",
            "total_amount_mining": "200000",
            "total_amount_others": "200000.00",
            "total_amount_costs": "-200000.00",
        },
        "billboard": {
            "walletcharts": [
                ["Income", 500000],
                ["Market Cost", 100000],
                ["Production Cost", 100000],
                ["Misc. Cost", 0],
            ],
            "charts": [],
            "rattingbar": [
                [
                    "x",
                    "2024-01",
                    "2024-02",
                    "2024-03",
                    "2024-04",
                    "2024-05",
                    "2024-06",
                    "2024-07",
                    "2024-08",
                    "2024-09",
                    "2024-10",
                    "2024-11",
                    "2024-12",
                ],
                [
                    "Ratting",
                    100000,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "ESS Payout",
                    0,
                    0,
                    1133333,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "Miscellaneous",
                    0,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    "Mining",
                    0,
                    0,
                    200000,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
            ],
            "workflowgauge": [
                ["Ratting", 16.3],
                ["ESS Payout", 61.8],
                ["Miscellaneous", 10.9],
                ["Mining", 10.9],
            ],
        },
    }
]
