# Generated by Django 4.2.28 on 2026-02-27 11:48

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("ledger", "0001_init_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterowner",
            name="eve_character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_character",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AlterField(
            model_name="corporationowner",
            name="eve_corporation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_corporationaudit",
                to="eveonline.evecorporationinfo",
            ),
        ),
    ]
