# Generated by Django 5.2.12 on 2026-03-30 07:22

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0018_alter_evecharacter_alliance_name_and_more"),
        ("ledger", "0002_alter_characterowner_eve_character_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllianceBillboardEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("xy_billboard", models.JSONField(default=None, null=True)),
                ("chord_billboard", models.JSONField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_alliance_billboard_entries",
                        to="eveonline.eveallianceinfo",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AllianceLedgerEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("bounty", models.FloatField(default=None, null=True)),
                ("ess", models.FloatField(default=None, null=True)),
                ("mining", models.FloatField(default=None, null=True)),
                ("miscellaneous", models.FloatField(default=None, null=True)),
                ("costs", models.FloatField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("corporation_id", models.IntegerField(default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_alliance_entry",
                        to="eveonline.eveallianceinfo",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CharacterBillboardEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("xy_billboard", models.JSONField(default=None, null=True)),
                ("chord_billboard", models.JSONField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_char_billboard_entries",
                        to="ledger.characterowner",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CharacterLedgerEntry",
            fields=[
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("bounty", models.FloatField(default=None, null=True)),
                ("ess", models.FloatField(default=None, null=True)),
                ("mining", models.FloatField(default=None, null=True)),
                ("miscellaneous", models.FloatField(default=None, null=True)),
                ("costs", models.FloatField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_character_entry",
                        to="ledger.characterowner",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CorporationBillboardEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("xy_billboard", models.JSONField(default=None, null=True)),
                ("chord_billboard", models.JSONField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_corp_billboard_entries",
                        to="ledger.corporationowner",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CorporationLedgerEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField(default=None, null=True)),
                ("month", models.PositiveSmallIntegerField(default=None, null=True)),
                ("day", models.PositiveSmallIntegerField(default=None, null=True)),
                ("bounty", models.FloatField(default=None, null=True)),
                ("ess", models.FloatField(default=None, null=True)),
                ("mining", models.FloatField(default=None, null=True)),
                ("miscellaneous", models.FloatField(default=None, null=True)),
                ("costs", models.FloatField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("final_data", models.BooleanField(default=False)),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("entity_id", models.IntegerField(default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_corporation_entry",
                        to="ledger.corporationowner",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "default_permissions": (),
            },
        ),
    ]
