# Generated by Django 5.2.13 on 2026-07-04 21:41

# Django
import django.db.models.deletion
from django.db import migrations, models


def _clean_duplicates(apps, schema_editor):
    """Remove duplicate EveMarketPrice entries, keeping only the one with the highest ID for each eve_type."""
    EveMarketPrice = apps.get_model("ledger", "EveMarketPrice")
    duplicates = (
        EveMarketPrice.objects.values("eve_type")
        .annotate(max_id=models.Max("id"), count=models.Count("id"))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        eve_type_id = duplicate["eve_type"]
        max_id = duplicate["max_id"]
        EveMarketPrice.objects.filter(eve_type=eve_type_id).exclude(id=max_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("ledger", "0003_alliancebillboardentry_allianceledgerentry_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=_clean_duplicates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="evemarketprice",
            name="eve_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
    ]
