# Generated by Django 5.2.13 on 2026-07-23 19:38

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("ledger", "0004_alter_evemarketprice_eve_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alliancebillboardentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_alliance_billboard",
                to="eveonline.eveallianceinfo",
            ),
        ),
        migrations.AlterField(
            model_name="allianceledgerentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_alliance",
                to="eveonline.eveallianceinfo",
            ),
        ),
        migrations.AlterField(
            model_name="characterbillboardentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_character_billboard",
                to="ledger.characterowner",
            ),
        ),
        migrations.AlterField(
            model_name="characterledgerentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_character",
                to="ledger.characterowner",
            ),
        ),
        migrations.AlterField(
            model_name="corporationbillboardentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_corporation_billboard",
                to="ledger.corporationowner",
            ),
        ),
        migrations.AlterField(
            model_name="corporationledgerentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_corporation",
                to="ledger.corporationowner",
            ),
        ),
    ]
