# Generated by Django 5.2.13 on 2026-09-20 14:23

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_alter_alliancebillboardentry_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app, Ledger."),
                    ("advanced_access", "Can access Corporation and Alliance Ledger."),
                    ("manage_access", "Can manage Ledger."),
                ),
                "verbose_name": "AA-Ledger",
                "verbose_name_plural": "AA-Ledger",
            },
        ),
    ]
