# Generated by Django 5.2.13 on 2026-10-03 23:55

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0036_remove_star_name"),
        ("ledger", "0006_alter_general_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alliancebillboardentry",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="allianceledgerentry",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="characterbillboardentry",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="characterledgerentry",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="corporationbillboardentry",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="corporationledgerentry",
            name="owner",
        ),
        migrations.AddIndex(
            model_name="characterminingledger",
            index=models.Index(
                fields=["character", "date"], name="ledger_char_charact_cd5f36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterwalletjournalentry",
            index=models.Index(
                fields=["character", "date"], name="ledger_char_charact_326126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporationwalletjournalentry",
            index=models.Index(
                fields=["division", "date"], name="ledger_corp_divisio_c4888f_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AllianceBillboardEntry",
        ),
        migrations.DeleteModel(
            name="AllianceLedgerEntry",
        ),
        migrations.DeleteModel(
            name="CharacterBillboardEntry",
        ),
        migrations.DeleteModel(
            name="CharacterLedgerEntry",
        ),
        migrations.DeleteModel(
            name="CorporationBillboardEntry",
        ),
        migrations.DeleteModel(
            name="CorporationLedgerEntry",
        ),
    ]
