# Generated by Django 4.2.26 on 2025-12-25 14:42

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0017_alter_eveentity_category_alter_eveentity_eve_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="characterplanet",
            name="ledger_char_planet__58a5b6_idx",
        ),
        migrations.RenameField(
            model_name="characterplanet",
            old_name="planet",
            new_name="eve_planet",
        ),
        migrations.RenameField(
            model_name="characterplanet",
            old_name="planet_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="corporationaudit",
            old_name="corporation",
            new_name="eve_corporation",
        ),
        migrations.AddIndex(
            model_name="characterplanet",
            index=models.Index(
                fields=["eve_planet"], name="ledger_char_eve_pla_d4379e_idx"
            ),
        ),
        migrations.RenameField(
            model_name="characterplanetdetails",
            old_name="facilitys",
            new_name="factories",
        ),
    ]
