# Generated by Django 4.2.26 on 2025-12-26 19:44

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        (
            "ledger",
            "0018_remove_characterplanet_ledger_char_planet__58a5b6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharacterAudit",
            new_name="CharacterOwner",
        ),
        migrations.RenameModel(
            old_name="CorporationAudit",
            new_name="CorporationOwner",
        ),
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="character",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="corporationupdatestatus",
            old_name="corporation",
            new_name="owner",
        ),
        migrations.AddIndex(
            model_name="characterwalletjournalentry",
            index=models.Index(
                fields=["character"], name="ledger_char_charact_fa27b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporationwalletjournalentry",
            index=models.Index(
                fields=["division"], name="ledger_corp_divisio_6ef4ce_idx"
            ),
        ),
    ]
