# Generated by Django 4.2.28 on 2026-02-26 12:04

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("ledger", "0019_rename_characteraudit_characterowner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterminingledger",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_evesolarsystem",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="characterminingledger",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_evetype",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="characterplanet",
            name="eve_planet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_planet",
                to="eve_sde.planet",
            ),
        ),
    ]
