# Generated by Django 4.2.28 on 2026-02-27 06:58

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("ledger", "0020_alter_characterminingledger_system_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adjusted_price", models.FloatField(default=None, null=True)),
                ("average_price", models.FloatField(default=None, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
