/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ledger/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the navigation menu of the current user */
        get: operations["ledger_api_general_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user and permissions */
        get: operations["ledger_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the settings of the current user */
        get: operations["ledger_api_general_get_user_settings"];
        /** Update the settings of the current user */
        put: operations["ledger_api_general_update_user_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/admin/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue an update for one or all characters/corporations */
        post: operations["ledger_api_general_queue_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all main characters visible to the user */
        get: operations["ledger_api_admin_get_character_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/planetary/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all main characters with planetary access */
        get: operations["ledger_api_admin_get_planetary_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/corporation/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all corporations visible to the user */
        get: operations["ledger_api_admin_get_corporation_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/alliance/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all alliances visible to the user */
        get: operations["ledger_api_admin_get_alliance_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/administration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the registered and missing characters of an account */
        get: operations["ledger_api_administration_get_character_administration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a character from the ledger */
        delete: operations["ledger_api_administration_delete_character"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/corporation/{corporation_id}/administration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the registration and members of a corporation */
        get: operations["ledger_api_administration_get_corporation_administration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/corporation/{corporation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a corporation from the ledger */
        delete: operations["ledger_api_administration_delete_corporation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/alliance/{alliance_id}/administration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the registered and missing corporations of an alliance */
        get: operations["ledger_api_administration_get_alliance_administration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ledger of a character and its alts */
        get: operations["ledger_api_character_get_character_ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/details/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the income and cost breakdown of a character */
        get: operations["ledger_api_character_get_character_ledger_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/planets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the planets of a character, optionally including its alts */
        get: operations["ledger_api_planetary_get_planetarydetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/planets/{planet_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get factories, storage and extractors of a planet */
        get: operations["ledger_api_planetary_get_planet_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/character/{character_id}/planets/notification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle the expiry notification of one or all planets */
        post: operations["ledger_api_planetary_toggle_planet_notification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/corporation/{corporation_id}/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ledger of a corporation, optionally for one division */
        get: operations["ledger_api_corporation_get_corporation_ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/corporation/{corporation_id}/details/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the income and cost breakdown of a corporation entity */
        get: operations["ledger_api_corporation_get_corporation_ledger_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/alliance/{alliance_id}/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ledger of an alliance and its corporations */
        get: operations["ledger_api_alliance_get_alliance_ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/api/alliance/{alliance_id}/details/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the income and cost breakdown of an alliance entity */
        get: operations["ledger_api_alliance_get_alliance_ledger_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MenuLink
         * @description A navigation link. `link` is relative to the app root unless `is_external` is set.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link: string;
            /** Badge */
            badge?: number | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
        };
        /** MenuSchema */
        MenuSchema: {
            /**
             * Left Links
             * @default []
             */
            left_links: components["schemas"]["MenuLink"][];
            /**
             * Right Links
             * @default []
             */
            right_links: components["schemas"]["MenuLink"][];
        };
        /**
         * ErrorSchema
         * @description Schema for error responses.
         */
        ErrorSchema: {
            /** Error */
            error: string;
        };
        /**
         * UserData
         * @description The current user, its main character and the permissions the UI depends on.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /**
             * Character Id
             * @default 0
             */
            character_id: number;
            /**
             * Character Name
             * @default
             */
            character_name: string;
            /**
             * Corporation Id
             * @default 0
             */
            corporation_id: number;
            /**
             * Corporation Name
             * @default
             */
            corporation_name: string;
            /** Alliance Id */
            alliance_id?: number | null;
            /** Alliance Name */
            alliance_name?: string | null;
            /** Portrait */
            portrait?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /**
             * Can Manage
             * @default false
             */
            can_manage: boolean;
            /**
             * Has Advanced Access
             * @default false
             */
            has_advanced_access: boolean;
        };
        /**
         * UserSettingsSchema
         * @description Notification settings of the current user.
         */
        UserSettingsSchema: {
            /** Disable Notifications */
            disable_notifications: boolean;
        };
        /**
         * UserSettingsUpdateRequest
         * @description User-editable notification preferences.
         */
        UserSettingsUpdateRequest: {
            /** Disable Notifications */
            disable_notifications: boolean;
        };
        /**
         * MessageSchema
         * @description Schema for simple success responses.
         */
        MessageSchema: {
            /** Message */
            message: string;
        };
        /**
         * AdminUpdateRequest
         * @description Request to queue an update. Without `eve_id` all owners of the target are updated.
         */
        AdminUpdateRequest: {
            /**
             * Target
             * @enum {string}
             */
            target: "characters" | "corporations";
            /** Eve Id */
            eve_id?: number | null;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /** CharacterOverview */
        CharacterOverview: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
        };
        /** CorporationOverview */
        CorporationOverview: {
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
        };
        /** AllianceOverview */
        AllianceOverview: {
            /** Alliance Id */
            alliance_id: number;
            /** Alliance Name */
            alliance_name: string;
        };
        /**
         * AdminOwnerSchema
         * @description A character, corporation or alliance in the administration lists.
         */
        AdminOwnerSchema: {
            /** Owner Id */
            owner_id: number;
            /** Name */
            name: string;
            /** Icon */
            icon?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * AdministrationResponse
         * @description Everything the administration page of an account, corporation or alliance shows.
         *
         *     Attributes:
         *         owner: The account's main character, corporation or alliance.
         *         dashboard: Registration statistics.
         *         registered: Entries registered in the ledger.
         *         missing: Entries that exist but are not registered.
         *         members: Characters of a corporation that are known to Auth.
         */
        AdministrationResponse: {
            owner: components["schemas"]["OwnerSchema"];
            dashboard: components["schemas"]["DashboardSchema"];
            /**
             * Registered
             * @default []
             */
            registered: components["schemas"]["AdminOwnerSchema"][];
            /**
             * Missing
             * @default []
             */
            missing: components["schemas"]["AdminOwnerSchema"][];
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["AltSchema"][];
        };
        /**
         * AltSchema
         * @description Alt character that is included in an entity's ledger.
         */
        AltSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Icon */
            icon?: string | null;
        };
        /**
         * DashboardSchema
         * @description Statistics shown on the administration dashboards.
         */
        DashboardSchema: {
            /** Auth Count */
            auth_count: number;
            /** Active Count */
            active_count: number;
            /** Inactive Count */
            inactive_count?: number | null;
            /** Missing Count */
            missing_count: number;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /**
         * OwnerSchema
         * @description Schema for Character or Character Owner.
         *
         *     Attributes:
         *         character_id (int): The ID of the character.
         *         character_name (str): The name of the character.
         *         icon (str | None): The URL of the character's icon, if available.
         */
        OwnerSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Icon */
            icon?: string | null;
        };
        /**
         * DateFilter
         * @description Date query parameters shared by all ledger endpoints, applied to `date`.
         */
        DateFilter: {
            /** Year */
            year: number;
            /** Month */
            month?: number | null;
            /** Day */
            day?: number | null;
        };
        /** BillboardData */
        BillboardData: {
            /** Categories */
            categories: {
                [key: string]: unknown;
            }[];
            /** Series */
            series: {
                [key: string]: unknown;
            }[];
        };
        /** BillboardSchema */
        BillboardSchema: {
            xy_chart?: components["schemas"]["BillboardData"] | null;
            chord_chart?: components["schemas"]["BillboardData"] | null;
        };
        /**
         * CharacterLedgerResponse
         * @description Schema for Character Ledger Response.
         *
         *     Attributes:
         *         characters (list[LedgerCharacterSchema]): List of character ledger data.
         */
        CharacterLedgerResponse: {
            owner: components["schemas"]["OwnerSchema"];
            billboard: components["schemas"]["BillboardSchema"];
            /**
             * Years
             * @default []
             */
            years: number[];
            /** Characters */
            characters: components["schemas"]["LedgerCharacterSchema"][];
        };
        /**
         * CharacterLedgerSchema
         * @description Schema for Character Ledger extending LedgerSchema.
         *
         *     Subclass of :class:`LedgerSchema`.
         *
         *     Attributes:
         *         mining (float): Amount related to mining activities.
         */
        CharacterLedgerSchema: {
            /**
             * Bounty
             * @default 0
             */
            bounty: number;
            /**
             * Ess
             * @default 0
             */
            ess: number;
            /**
             * Costs
             * @default 0
             */
            costs: number;
            /**
             * Miscellaneous
             * @default 0
             */
            miscellaneous: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Mining
             * @default 0
             */
            mining: number;
        };
        /** LedgerCharacterSchema */
        LedgerCharacterSchema: {
            character: components["schemas"]["OwnerSchema"];
            ledger: components["schemas"]["CharacterLedgerSchema"];
            update_status: components["schemas"]["UpdateStatusSchema"];
        };
        /** UpdateStatusSchema */
        UpdateStatusSchema: {
            /** Last Update */
            last_update?: string | null;
            /** Last Run */
            last_run?: string | null;
            /** Status */
            status?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /** CategorySchema */
        CategorySchema: {
            /** Name */
            name: string;
            /**
             * Amount
             * @default 0
             */
            amount: number;
            /**
             * Average
             * @default 0
             */
            average: number;
            /**
             * Average Tick
             * @default 0
             */
            average_tick: number;
            /**
             * Ref Types
             * @default []
             */
            ref_types: components["schemas"]["RefTypeAmountSchema"][];
        };
        /**
         * LedgerDetailsResponse
         * @description Flexible schema for detailed ledger categories.
         *
         *     Attributes:
         *         summary (CategorySchema): Summary of all categories.
         *         daily (CategorySchema): Daily breakdown of categories.
         *         hourly (CategorySchema): Hourly breakdown of categories.
         */
        LedgerDetailsResponse: {
            /** Summary */
            summary: components["schemas"]["CategorySchema"][];
            /** Daily */
            daily: components["schemas"]["CategorySchema"][];
            /** Hourly */
            hourly: components["schemas"]["CategorySchema"][];
            total: components["schemas"]["LedgerDetailsSummary"];
        };
        /**
         * LedgerDetailsSummary
         * @description Schema for the totals of ledger details.
         *
         *     Attributes:
         *         summary (float): Total of all categories.
         *         daily (float): Daily average of all categories.
         *         hourly (float): Hourly average of all categories.
         */
        LedgerDetailsSummary: {
            /**
             * Summary
             * @default 0
             */
            summary: number;
            /**
             * Daily
             * @default 0
             */
            daily: number;
            /**
             * Hourly
             * @default 0
             */
            hourly: number;
        };
        /**
         * RefTypeAmountSchema
         * @description Amount that a single reference type contributed to a category.
         */
        RefTypeAmountSchema: {
            /** Ref Type */
            ref_type: string;
            /**
             * Amount
             * @default 0
             */
            amount: number;
        };
        /**
         * PlanetSelection
         * @description Selects one planet, or all planets of the character if omitted.
         */
        PlanetSelection: {
            /** Planet Id */
            planet_id?: number | null;
        };
        /**
         * EveTypeSchema
         * @description Schema for EVE Online item types.
         *
         *     Attributes:
         *         id (int): The ID of the item type.
         *         name (str): The name of the item type.
         *         description (str | None): The description of the item type, if available.
         *         group_id (int | None): The group ID of the item type, if available.
         *         group_name (str | None): The group name of the item type, if available.
         *         market_group_id (int | None): The market group ID of the item type, if available.
         *         market_group_name (str | None): The market group name of the item type, if available.
         *         icon (str | None): The URL of the item type's icon, if available.
         */
        EveTypeSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Group Id */
            group_id?: number | null;
            /** Group Name */
            group_name?: string | null;
            /** Market Group Id */
            market_group_id?: number | null;
            /** Market Group Name */
            market_group_name?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /** PlanetSchema */
        PlanetSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["EveTypeSchema"];
            /** Upgrade Level */
            upgrade_level: number;
            /** Num Pins */
            num_pins: number;
            /** Last Update */
            last_update?: string | null;
        };
        /**
         * PlanetaryDetails
         * @description A planet of a character. `id` is the identifier for the detail and notification endpoints.
         */
        PlanetaryDetails: {
            /** Id */
            id: number;
            owner: components["schemas"]["OwnerSchema"];
            planet: components["schemas"]["PlanetSchema"];
            /** Expired */
            expired: boolean;
            /** Alarm */
            alarm: boolean;
            /** Progress */
            progress?: number | null;
            /** Factories */
            factories: components["schemas"]["ProduceSchema"][];
        };
        /** ProduceSchema */
        ProduceSchema: {
            /** Factory Name */
            factory_name: string;
            /** Input Products */
            input_products: components["schemas"]["ProductSchema"][];
            output_product?: components["schemas"]["ProductSchema"] | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ProductSchema */
        ProductSchema: {
            /** Item Id */
            item_id: number;
            /** Item Name */
            item_name: string;
            /** Item Quantity */
            item_quantity?: number | null;
            /** Icon */
            icon?: string | null;
        };
        /** ExtractorSchema */
        ExtractorSchema: {
            /** Item Id */
            item_id: number;
            /** Item Name */
            item_name: string;
            /** Icon */
            icon?: string | null;
            /** Install Time */
            install_time: string;
            /** Expiry Time */
            expiry_time: string;
            /** Progress */
            progress: number;
        };
        /** PlanetDetailResponse */
        PlanetDetailResponse: {
            owner: components["schemas"]["OwnerSchema"];
            planet: components["schemas"]["PlanetSchema"];
            /** Factories */
            factories: components["schemas"]["ProduceSchema"][];
            /** Storage */
            storage: components["schemas"]["StorageSchema"][];
            /** Extractors */
            extractors: components["schemas"]["ExtractorSchema"][];
        };
        /** StorageSchema */
        StorageSchema: {
            /** Factory Name */
            factory_name: string;
            product: components["schemas"]["ProductSchema"];
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** Message */
            message: string;
            /** Notification */
            notification: boolean;
        };
        /**
         * CorporationLedgerFilter
         * @description Query parameters for corporation ledgers, optionally limited to one division.
         */
        CorporationLedgerFilter: {
            /** Year */
            year: number;
            /** Month */
            month?: number | null;
            /** Day */
            day?: number | null;
            /** Division Id */
            division_id?: number | null;
        };
        /**
         * AltLedgerSchema
         * @description Contribution of one alt character to the ledger of its entity.
         */
        AltLedgerSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Icon */
            icon?: string | null;
            ledger: components["schemas"]["LedgerSchema"];
        };
        /**
         * CorporationLedgerResponse
         * @description Schema for Corporation Ledger Response.
         *
         *     Attributes:
         *         entities (list[LedgerEntitySchema]): The list of ledger entities.
         *         divisions (list[DivisionSchema]): The wallet divisions to choose from.
         */
        CorporationLedgerResponse: {
            owner: components["schemas"]["OwnerSchema"];
            billboard: components["schemas"]["BillboardSchema"];
            /**
             * Years
             * @default []
             */
            years: number[];
            /** Entities */
            entities: components["schemas"]["LedgerEntitySchema"][];
            /**
             * Divisions
             * @default []
             */
            divisions: components["schemas"]["DivisionSchema"][];
        };
        /**
         * DivisionSchema
         * @description A wallet division of a corporation.
         */
        DivisionSchema: {
            /** Division Id */
            division_id: number;
            /** Name */
            name: string;
        };
        /**
         * EntitySchema
         * @description Schema for Entity or Corporation Owner.
         *
         *     Attributes:
         *         entity_id (int): The ID of the entity.
         *         entity_name (str): The name of the entity.
         *         alt_ids (list[int]): The IDs of all characters included in the entity.
         *         alts (list[AltSchema]): The alt characters included in the entity.
         *         icon (str | None): The URL of the entity's icon, if available.
         */
        EntitySchema: {
            /** Entity Id */
            entity_id: number;
            /** Entity Name */
            entity_name: string;
            /**
             * Alt Ids
             * @default []
             */
            alt_ids: number[];
            /**
             * Alts
             * @default []
             */
            alts: components["schemas"]["AltSchema"][];
            /** Icon */
            icon?: string | null;
            /** Is Member */
            is_member?: boolean;
        };
        /** LedgerEntitySchema */
        LedgerEntitySchema: {
            entity: components["schemas"]["EntitySchema"];
            ledger: components["schemas"]["LedgerSchema"];
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["AltLedgerSchema"][];
        };
        /**
         * LedgerSchema
         * @description Schema for Ledger Summary.
         *
         *     Attributes:
         *         bounty (float): Amount related to bounties.
         *         ess (float): Amount related to ESS activities.
         *         costs (float): Amount related to costs.
         *         miscellaneous (float): Miscellaneous amount.
         *         total (float): Total amount.
         */
        LedgerSchema: {
            /**
             * Bounty
             * @default 0
             */
            bounty: number;
            /**
             * Ess
             * @default 0
             */
            ess: number;
            /**
             * Costs
             * @default 0
             */
            costs: number;
            /**
             * Miscellaneous
             * @default 0
             */
            miscellaneous: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * AllianceLedgerResponse
         * @description Schema for Alliance Ledger API Response
         *
         *     Attributes:
         *         corporations (list[LedgerAllianceSchema]): A list of ledger entities associated with the alliance.
         */
        AllianceLedgerResponse: {
            owner: components["schemas"]["OwnerSchema"];
            billboard: components["schemas"]["BillboardSchema"];
            /**
             * Years
             * @default []
             */
            years: number[];
            /** Corporations */
            corporations: components["schemas"]["LedgerAllianceSchema"][];
        };
        /** LedgerAllianceSchema */
        LedgerAllianceSchema: {
            corporation: components["schemas"]["EntitySchema"];
            ledger: components["schemas"]["LedgerSchema"];
            update_status?: components["schemas"]["UpdateStatusSchema"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ledger_api_general_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_general_get_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_general_update_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_general_queue_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_admin_get_character_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOverview"][];
                };
            };
        };
    };
    ledger_api_admin_get_planetary_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOverview"][];
                };
            };
        };
    };
    ledger_api_admin_get_corporation_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationOverview"][];
                };
            };
        };
    };
    ledger_api_admin_get_alliance_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceOverview"][];
                };
            };
        };
    };
    ledger_api_administration_get_character_administration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdministrationResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_administration_delete_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_administration_get_corporation_administration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdministrationResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_administration_delete_corporation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_administration_get_alliance_administration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdministrationResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_character_get_character_ledger: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
                day?: number | null;
            };
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLedgerResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_character_get_character_ledger_details: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
                day?: number | null;
                section?: "single" | "summary";
            };
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerDetailsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_planetary_get_planetarydetails: {
        parameters: {
            query?: {
                planet_id?: number | null;
                single?: boolean;
            };
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetaryDetails"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_planetary_get_planet_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanetDetailResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_planetary_toggle_planet_notification: {
        parameters: {
            query?: {
                planet_id?: number | null;
            };
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_corporation_get_corporation_ledger: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
                day?: number | null;
                division_id?: number | null;
            };
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationLedgerResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_corporation_get_corporation_ledger_details: {
        parameters: {
            query: {
                entity_id: number;
                year: number;
                month?: number | null;
                day?: number | null;
                division_id?: number | null;
                section?: "single" | "summary";
            };
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerDetailsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_alliance_get_alliance_ledger: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
                day?: number | null;
            };
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceLedgerResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    ledger_api_alliance_get_alliance_ledger_details: {
        parameters: {
            query: {
                entity_id: number;
                year: number;
                month?: number | null;
                day?: number | null;
                section?: "single" | "summary";
            };
            header?: never;
            path: {
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerDetailsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
}
