# Variables
# Configuration file for the AA Example project

[General]
appname = aa-example
appname_verbose = AA Example
package = example

[DB]
mysql_executable = /usr/bin/mysql
mysqldump_executable = /usr/bin/mysqldump
backup_directory = .
name = alliance_testing
host = localhost
port = 3306
user = allianceserver
password =

[Development]
base_dir = .
test_db_name = test_alliance_testing

[Django]
myauth_path = ../myauth
translation_directory = $(GENERAL__PACKAGE)/locale
translation_template = $(GENERAL__PACKAGE)/locale/django.pot
translation_file_relative_path = LC_MESSAGES/django.po

[Git]
git_repository = https://github.com/Geuthur/$(GENERAL__APPNAME)
git_repository_issues = https://github.com/Geuthur/$(GENERAL__APPNAME)/issues

[Python]
executable = ../venv/bin/python
venv_path = ../venv

[Weblate]
base_url = https://weblate.geuthur.de
project_slug = alliance-auth
component_slug = $(GENERAL__APPNAME)
