name: Release

on:
  release:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    types: [released, prereleased]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    environment:
      name: pypi-release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade setuptools wheel

      - name: Build Package
        run: |
          python -m build

      - name: Add Assets to Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1